kinematics:
    hash: calib_9850083849278483356
    shoulder:
      x: 0
      y: 0
      z: 0.1624103536614592
      roll: -0
      pitch: 0
      yaw: -5.419454664201684e-08
    upper_arm:
      x: 5.507674938472934e-05
      y: 0
      z: 0
      roll: 1.569964621969524
      pitch: 0
      yaw: 2.331832274706031e-06
    forearm:
      x: -0.4252313365840755
      y: 0
      z: 0
      roll: 3.140075376303109
      pitch: 3.139267151936045
      yaw: -3.141591960117041
    wrist_1:
      x: -0.3924806308977182
      y: 0.0002678675780774199
      z: 0.1339362616574212
      roll: 3.139592693178625
      pitch: -3.139808949100953
      yaw: -3.141592630891463
    wrist_2:
      x: -2.180832054162689e-05
      y: -0.0996776560975477
      z: 3.162570471885324e-05
      roll: 1.570479047026333
      pitch: 0
      yaw: -8.254839444204327e-07
    wrist_3:
      x: 0.0001767036867879324
      y: 0.0996790491118911
      z: 0.0001705059604350208
      roll: 1.572506874755129
      pitch: 3.141592653589793
      yaw: 3.141592625169862